### ISSUE TITLE
1. 서비스 개요

### ISSUE THREAD

**Issue by Jo-Seungjun** [Jo-Seungjun/APP_CHALLENGE#3]
# 가. 서비스 개념 
※ 게임 명 및 게임의 개요를 6하 원칙에 따라 핵심 단어 중심으로 간략히 작성
   : 고객, 제공 가치, 기술구현, 제공 방법 등

# 나. 서비스 주제 및 기획 의도
※ 게임의 세계관 및 주제를 설명하고, 게임을 기획한 의도에 대해 설명

# 다. 주요 타겟 고객
※ 이 게임은 누가 쓸 것인가? 사용자에게 어떤 가치가치(혜택)를 줄 수 있는가?

# 라. 주요 서비스 내용 ※ (최대한 구체적으로 기술)
   1) 게임 시나리오
 
   2) 조작 방법
     ※ 게임 진행 방법 및 정보 설명 (반드시 이미지와 함께 설명)

   3) 기타 게임 구현시 필요 사항
   ※ 디자인, 캐릭터, 플레이, 그래픽, 사운드 컨셉 등

**Comment by Jo-Seungjun** [comment]
이거 온라인으로 해서 비슷한 감정이 있는 사람끼리는 비슷한 지역에 묶이게 하자!
그러면 감정 공감도 되고 효과가 더욱 증가할 것 같아

**Comment by Jo-Seungjun** [comment]
##서비스 개념
E'Motion 은 플레이어의 감정을 다양한 센서와 개인정보(페이스북, 메신저, 트위터)를 통해 추척하고 게임을 플레이하면서 자신의 감정을 게임과 공감할 수 있도록 게임의 형태와 환경및 디자인이 변하는 초 반응적인 모험게임 입니다.
1) 장르 : 모험
2) 플렛폼 : 스마트 폰, 웹, --IoT인형--
3) 사용엔진 : ??
4) 제공방법 : 웹을통해 체험판 제공, 구글 플레이스토어를 통해 정식판 배포

**Comment by Min-Moon-Ki** [comment]
##주요 타겟 고객

이 게임의 주요 타겟 고객은 
 - 다른사람들과의 관계를 개선하고싶은 사람들
 - 감정을 숨겨야하는 현대사회에 지친 사람들
 - 휴식처가 필요한사람
 - (추가)
입니다.

**Comment by Jo-Seungjun** [comment]
# 주요 타겟 고객
| 순위 | 타겟유저 | 특징 | 소비 전략 | 주요 플레이어 |
| ----- | ---------- | ----- | ----------- | ---------------- |

**Comment by Jo-Seungjun** [comment]
# 주요 서비스 내용
1. 게임 시나리오

 `여기서부터 엄청난 양을 추가해야함`

**Comment by Jo-Seungjun** [comment]
# 서비스 주제 및 기획 의도 No.2
1. 주제
 이 게임은 플레이어와 공감하는것을 목표로 하고 있습니다. 게임을 플레이 하는 동안 게임은 플레이어를 이해하기위해 다양한 방법을 사용합니다. 플레이어를 이해한 게임은 플레이어가 무엇을 원하는지 예측하고 가끔은 정신적으로 건강한 상태를 만들어 주기 위해 플레이어를 이끌어 줍니다.
