### ISSUE TITLE
2. 서비스 경쟁력/차별화

### ISSUE THREAD

**Issue by Jo-Seungjun** [Jo-Seungjun/APP_CHALLENGE#4]
가. 경쟁(유사) 서비스 현황
※ (유사한 어플/서비스 현황, 기존 시장 규모 및 확장 가능성)

나. 경쟁(유사) 서비스 대비 차별화 요소 
   ※ 고객이 느끼는 타 서비스 대비 차별화 요소 (예시)
       - 기존 서비스 대비 고객의 시간을 줄여 준다.       
       - 사용자 편의성을 획기적으로 개선 했했다.(UI/UX 등)
       - 아주 편리하고 새로운 기술을 적용했다.
         (저작권/특허가 있는 경우 명기)

**Comment by Jo-Seungjun** [comment]
### 비슷한 유형의 게임들
- journey : 두명의 유저가 걸어나가는 게임
- my oasis : 음을 들려주어 자신의 별을 조작하는 게임

**Comment by Jo-Seungjun** [comment]
## 경쟁(유사) 서비스 현황
- journey
 - 랜덤으로 연결된 두명의 유저가 모험을 하는 게임 이다. 두명의 유저는 구체적인 목표 없이 하늘에있는 빛을 향해 모험을 떠나는데 그 과정에서 아름다운 경험들을 서로 공유하고 겪으면서 치유를 받게 한다.
- my oasis
 - 음을 들려주면 그에따라 행성이 변하는 게임으로 게임을 플레이하다보면 퀘스트의 이름 에서도 사용자를 자기개발하는 목표가 있으며 등장하는 동물들도 직설적으로 사용자에게 도움이 되는 말을 해준다.
- rime
 - 한 소년이 여행을 하면서 생각치도 못한 이벤트 들과 경험을 하면서 아름다운 자연을 관광한다.

**Comment by Min-Moon-Ki** [comment]
# 경쟁(유사) 서비스 대비 차별화 요소 
E’motion은 my oasis와 같이 꾸며가는 게임이 아닙니다. 또한 rime과 같이 퍼즐을 푸는 것도 아니지요. E’motion은 플레이어의 심리상태를 분석하고 그에 따라 이야기를 만들고 자기개발을 할 수 있는 게임 입니다.
1)	플레이어의 성격, 성향, 감정을 분석하여 공감을 극대화 한다.
E’motion은 힐링의 방안으로 플레이어가 게임을 따라가는 것이 아닌 게임이 플레이어를 맞춰주는 것을 목표로 하고 있습니다. 그렇기 때문에 성격 검사지나 심리 검사지를 게임내에 도입하는 것 입니다. 또한 플레이어의 행동분석을 통해 취향을 알아내고 그에 따라 스토리가 변하게 됩니다.
2)	플레이어의 성향에 따른 적절한 스토리를 만들어 낸다.
E’motion의 스토리는 플레이어의 감정을 따라갑니다. 이 스토리는 감정의“단계” 라는 것이 존재할 뿐 세부적으로 명시 되어있지 않습니다. 세부적인 스토리는 플레이어가 만들어 내는 것인데 사용자가 설문에 적극적으로 참여했고 그에 맞는 행동으로 플레이했다면 그 설문에 기반하여 이벤트가 옴니버스 식으로 나타납니다. (플레이어가 강아지를 좋아한다면 강아지와 관련된 이벤트가 나타남)
3)	조작이 간편하다.
E’motion은 캐릭터를 움직이는 버튼 외에 별다른 기능이 없어 직관적인 플레이가 가능합니다.
