### ISSUE TITLE
웹앱 vs 앱

### ISSUE THREAD

**Issue by Jo-Seungjun** [Jo-Seungjun/APP_CHALLENGE#7]
이 게임을 배포할 때 어떤 방식으로 배포할지 결정해야 합니다.
궁극적인 서비스 목표는 플레이어가 게임에 접속하여 문서 음성 사진 등의 데이터를 주고 받을 수 있어야 합니다.
처음에 주요 플레이어를 모바일 유저로 두고 상의했기 때문에 모바일에서 접근 가능한 application 형태로 배포하려 했으나 더 많은 사용자를 모으기 위해서 web application 의 형태로 배포해도 괜찮을것 같았습니다.

우선 앱 이란 안드로이드 휴대폰에 설치되어 실행할 수 있는 프로그램을 말하며 프로그래머 입장에서 하드웨어에 접근하기 편리하며 3D엔진 Unity 로 개발 할 수 있습니다.

웹앱은 플레이어가 인터넷 브라우저를 통해 웹페이지를 받아와 인터넷 브라우징 상태에서 프로그램을 사용할 수 있는것을 말하며 브라우저의 성능 또는 지원하는 기능에 따라 하드웨어의 접근이 달라질 수 있습니다.

여기서 기억할 것은 이 게임은 힐링게임이며 틈세시간을 활용하여 플레이하는것을 생각하고 있습니다. 이 틈세시간이란 컴퓨터 앞서 쉬는시간 만을 포함하지 않고 이동중이거나 잠시 쉬는 시간등을 의미하는데 이런 간 중 인터넷에 연결되어 있을 가능성이 높은 시간이 많지 않습니다. 또한 여가를 즐기기 위해 데이터를 소모하는것은 부담감이 있기도 합니다.

**Comment by Min-Moon-Ki** [comment]
확실히 인터넷을 항상 사용해야하는건 부담되니 앱을 만들고 동의를 얻어 인터넷에 연결하는게 좋겠네요
